    CREATE TABLE [dbo].[Profiles]
    (
        [Id] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY, 
        [FirstName] NVARCHAR(1000) NOT NULL, 
        [LastName] NVARCHAR(1000) NOT NULL, 
        [UserName] NVARCHAR(1000) NULL, 
        [Email ] NVARCHAR(1000) NULL, 
        [Password] NVARCHAR(MAX) NULL, 
        [ImageUrl] NVARCHAR(100) NULL,
        [ProfileType] INT NOT NULL,
        [CreatedAt] DATETIME2 NULL, 
        [CreatedBy] INT NULL, 
        [LastUpdatedAt] DATETIME2 NULL, 
        [LastUpdatedBy] INT NULL, 
        [LastSeen] DATETIME2 NULL DEFAULT GETDATE(), 
        [DesignationId] INT NOT NULL DEFAULT 1 , 
        [StatusId] INT NULL DEFAULT 1,
        CONSTRAINT [FK_Profiles_UerStatus_To_Status] FOREIGN KEY ([StatusId]) REFERENCES dbo.Status(Id),
        CONSTRAINT [FK_Profiles_DesignationId_To_Designations] FOREIGN KEY ([DesignationId]) REFERENCES dbo.Designations(Id),
    )
